FROM python:3.7-slim-buster

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y git build-essential cmake libprotobuf-dev protobuf-compiler
COPY ./ ./TenSEAL
WORKDIR /TenSEAL
RUN pip3 install .

ENTRYPOINT [ "/bin/bash" ]
