FROM python:3.6-slim-buster

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y git build-essential cmake
COPY ./ ./TenSEAL
WORKDIR /TenSEAL
# 3rd party libraries
RUN git submodule init && git submodule update
RUN pip3 install .

ENTRYPOINT [ "/bin/bash" ]
