name: Linux Package

on:
  release:
    types: [created]

jobs:
  deploy:
    strategy:
      matrix:
        python-version:
          - cp36-cp36m
          - cp37-cp37m
          - cp38-cp38

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_x86_64

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Set target Python version PATH
        run: echo "::add-path::/opt/python/${{ matrix.python-version }}/bin"
      - name: Install dependencies
        run: .github/workflows/scripts/install_req_centos.sh
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: .github/workflows/scripts/release_centos.sh
