name: Linux Package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    strategy:
      matrix:
        python-version:
          - cp38-cp38
          - cp39-cp39
          - cp310-cp310
          - cp311-cp311
          - cp312-cp312

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    
    # node20 can't run on manylinux2014 as it requires newer version of GLIBC
    # https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
    env:
      ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          submodules: true
      - name: Prepare ENV
        run: |
            echo "/opt/python/${{ matrix.python-version }}/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: .github/workflows/scripts/install_req_centos.sh
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: .github/workflows/scripts/release_centos.sh
