name: Linux Package

on:
  release:
    types: [created]

jobs:
  deploy:
    strategy:
      matrix:
        python-version:
          - cp37-cp37m
          - cp38-cp38
          - cp39-cp39
          - cp310-cp310

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Prepare ENV
        run: |
            echo "/opt/python/${{ matrix.python-version }}/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: .github/workflows/scripts/install_req_centos.sh
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: .github/workflows/scripts/release_centos.sh
